# 1. Use Corretto 17 on Alpine Linux as the base
FROM amazoncorretto:17-alpine

# 2. Set working directory inside the container
WORKDIR /app

# 3. Copy the fat JAR into the image
COPY target/*.jar app.jar

# 4. Tell Docker how to start your Spring Boot app
ENTRYPOINT ["java","-jar","app.jar"]
