name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vitanova-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # ← NEW: configure AWS creds so the login action can read AWS_REGION
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-2

      # ← UPDATED: no 'region:' input, instead supply your ECR registry URI
      - name: Authenticate to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Build and push Docker image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          IMAGE_NAME: vitanova-backend
          AWS_REGION: us-east-2
        run: |
          # Compose the full registry URI here
          REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          echo "Registry: $REGISTRY"
          echo "Image : $IMAGE_NAME:latest"

          # Now build & push
          docker build -t ${REGISTRY}/${IMAGE_NAME}:latest .
          docker push ${REGISTRY}/${IMAGE_NAME}:latest



