name: CI/CD Pipeline (App Runner)

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: vitanova-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Configure AWS credentials (static keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-2

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2
        # no 'registries:' needed; it uses the current account

      - name: Ensure mvnw is executable (and LF)
        run: |
          sed -i 's/\r$//' mvnw || true
          chmod +x mvnw

      - name: Build Spring Boot JAR
        run: ./mvnw -q -B -U clean package -DskipTests

      - name: Build & push Docker image (:prod only)
        env:
          ECR_REGISTRY:  ${{ steps.ecr.outputs.registry }}
          ECR_REPOSITORY: vitanova-backend
          JAR_FILE:      target/vitanova-backend-0.0.1-SNAPSHOT.jar
        run: |
          docker build --build-arg JAR_FILE="$JAR_FILE" \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:latest" .
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:latest"



